import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // Load saved language preference or default to English
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    // Save language preference
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Translations object
const translations = {
  en: {
    // Navbar
    'nav.marketplace': 'Mandi Market',
    'nav.dashboard': 'Farmer Studio',
    'nav.orders': 'Orders',
    'nav.tracking': 'Dispatch Track',
    'nav.login': 'Login / Register',
    'nav.logout': 'Logout',
    'nav.tagline': 'Direct Farmer to Consumer Network',
    'nav.role.farmer': '🌾 Kisan / FPO',
    'nav.role.buyer': '🛒 Buyer',

    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort By',
    'common.viewAll': 'View All',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.emailAddress': 'Email Address',
    'common.password': 'Password',
    'common.login': 'Login',
    'common.price': 'Price',
    'common.pending': 'Pending',
    'common.totalAmount': 'Total Amount',
    'common.payment': 'Payment',
    'common.saving': 'Saving…',
    'common.saveChanges': 'Save Changes',
    'common.continue': 'Continue →',
    'common.confirmOrder': 'Confirm Order',
    'common.minutes': ' mins',

    // Login Page
    'login.title': 'Welcome to AgriConnect',
    'login.subtitle': 'Direct Farm-to-Consumer Trade Network',
    'login.selectRole': 'Select Your Role',
    'login.farmer': 'Farmer / FPO',
    'login.farmerDesc': 'List your harvest and connect with buyers',
    'login.buyer': 'Buyer (Consumer/Bulk)',
    'login.buyerDesc': 'Browse fresh produce directly from farms',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.name': 'Full Name',
    'login.phone': 'Phone Number',
    'login.location': 'Location',
    'login.signIn': 'Sign In',
    'login.signUp': 'Create Account',
    'login.switchToSignUp': 'New user? Create an account',
    'login.switchToSignIn': 'Already have an account? Sign in',

    // Login extras
    'login.badge.tagline': 'Kisan Se Seedha Mandi & Grahak',
    'login.hero.title': 'Welcome to AgriConnect',
    'login.hero.description': 'Direct trade network ensuring fair MSP returns to agricultural producers and authentic farm-fresh supply to buyers.',
    'login.roleSelector.title': 'Select Account Type',
    'login.role.farmerTitle': 'Kisan / FPO Producer',
    'login.role.farmerDesc': 'List harvests, view mandi price trends & receive direct payments.',
    'login.role.buyerTitle': 'Buyer / Retail / Bulk',
    'login.role.buyerDesc': 'Order farm-fresh produce with live cold-chain tracking.',
    'login.trust.verifiedKisan': 'Verified Kisan Aadhaar & FPO Registration',
    'login.trust.zeroBrokerage': 'Zero Brokerage & Direct Bank UPI Settlement',
    'login.tabs.login': 'Login',
    'login.tabs.register': 'Register',
    'login.heading.signIn': 'Sign in with Email',
    'login.heading.registerRoleFarmer': 'Register as Farmer / FPO',
    'login.heading.registerRoleBuyer': 'Register as Buyer',
    'login.subheading.signIn': 'Enter your email and password to sign in.',
    'login.subheading.register': 'Enter your basic contact & location details to get started.',
    'login.placeholder.email': 'e.g. farmer@example.com',
    'login.button.signingIn': 'Signing in...',
    'login.button.signIn': 'Sign In',
    'login.label.fullName': 'Full Name / Adhikrit Naam',
    'login.placeholder.nameFarmer': 'e.g. Ramesh Kumar Patel',
    'login.placeholder.nameBuyer': 'e.g. Sunil Sharma',
    'login.placeholder.passwordMin': 'Minimum 6 characters',
    'login.label.mobileNumber': 'Mobile Number',
    'login.placeholder.mobileNumber': '10-digit number',
    'login.label.location': 'District & State',
    'login.placeholder.location': 'e.g. Ludhiana, Punjab',
    'login.label.fpoName': 'FPO / Cooperative Group Name (Optional)',
    'login.placeholder.fpoName': 'e.g. Malwa Kisan Vikas Cooperative',
    'login.label.buyerCategory': 'Buyer Category',
    'login.buyerType.consumer': 'Individual Household / Consumer',
    'login.buyerType.restaurant': 'Restaurant / Commercial Kitchen',
    'login.buyerType.trader': 'Wholesale Mandi Trader (B2B)',
    'login.buyerType.supermarket': 'Retail Supermarket Chain',
    'login.button.completeRegistration': 'Complete Registration & Enter',
    'login.footer.terms': 'By signing in, you agree to the Fair Mandi Trade Terms & Direct Settlement Rules under SIH 26033.',
    'login.alert.enterCredentials': 'Please enter both email and password.',
    'login.alert.authFailed': 'Authentication failed. Please check your credentials.',

    // Marketplace
    'marketplace.title': 'Direct Farm Produce Marketplace',
    'marketplace.subtitle': 'Fresh from Farms • Zero Middlemen • Fair Prices',
    'marketplace.searchPlaceholder': 'Search crops, farmers, locations...',
    'marketplace.noProducts': 'No products found',
    'marketplace.browseMessage': 'Check back soon or adjust your filters',
    'marketplace.perKg': '/kg',
    'marketplace.available': 'Available',
    'marketplace.orderNow': 'Order Now',
    'marketplace.quantityPlaceholder': 'Quantity (kg)',
    'marketplace.placeOrder': 'Place Order',
    'marketplace.totalPrice': 'Total Price',
    'marketplace.paymentMethod': 'Payment Method',
    'marketplace.upi': 'UPI / Card',
    'marketplace.cod': 'Cash on Delivery',

    // Marketplace extras
    'marketplace.error.addressRequired': 'Please enter a delivery address.',
    'marketplace.badge.directFarm': 'Direct Farm',
    'marketplace.badge.organicCertified': 'Organic Certified',
    'marketplace.product.stock': 'Stock:',
    'marketplace.product.producer': 'Producer:',
    'marketplace.product.mandiHub': 'Mandi Hub 04',
    'marketplace.product.directFarmPrice': 'Direct Farm Price',
    'marketplace.product.available': 'Available',
    'marketplace.button.buyDirect': 'Buy Direct',
    'marketplace.button.sellingOnly': 'Selling only',
    'marketplace.tooltip.sellerOnly': 'Seller accounts list crops — use a separate buyer account to order.',
    'marketplace.tooltip.loginRequired': 'Login as a buyer to place orders.',
    'marketplace.alert.loginRequired': 'Please login first to place an order',
    'marketplace.alert.orderSuccess': 'Order placed successfully! Payment:',
    'marketplace.alert.orderFailed': 'Failed to place order:',
    'marketplace.banner.subtag': 'DIRECT FARM MANDI MARKETPLACE • 0% MIDDLEMAN COMMISSIONS',
    'marketplace.banner.title': 'Farm-Fresh Mandi Harvests',
    'marketplace.banner.desc': 'Browse authentic lots directly from verified FPOs and local agricultural cooperatives.',
    'marketplace.banner.verifiedFPOs': 'Verified FPOs',
    'marketplace.banner.activeFPOs': '12 Active',
    'marketplace.banner.transitEta': 'Transit ETA',
    'marketplace.banner.sameDay': 'Same Day',
    'marketplace.search.placeholder': 'Search crop, farmer, or district...',
    'marketplace.empty.title': 'No farm harvests match your search criteria.',
    'marketplace.empty.clearFilters': 'Clear Filters',
    'marketplace.button.myOrders': 'My Orders',
    'category.all': 'All',
    'category.vegetables': 'Vegetables',
    'category.grains': 'Grains',
    'category.fruits': 'Fruits',
    'category.dryFruits': 'Dry Fruits',
    'category.dryfruits': 'Dry Fruits',
    'category.other': 'Others',

    // Payment methods
    'payment.upi.label': 'UPI',
    'payment.upi.sub': 'GPay / PhonePe / Paytm',
    'payment.card.label': 'Card',
    'payment.card.sub': 'Credit / Debit',
    'payment.netbanking.label': 'Net Banking',
    'payment.netbanking.sub': 'All major banks',
    'payment.wallet.label': 'Wallet',
    'payment.wallet.sub': 'Paytm / Amazon Pay',
    'payment.cod.sub': 'Pay at your doorstep',
    'payment.methodLabel': 'Payment Method',

    // Order modal (marketplace)
    'order.modal.title': 'Place Order',
    'order.modal.quantityIn': 'Quantity (in',
    'order.modal.deliveryAddress': 'Delivery Address',
    'order.modal.addressPlaceholder': 'House no, street, city, state',
    'order.modal.saveAddressDefault': 'Save this as my default delivery address',
    'order.modal.totalPayableOnline': 'Total Payable',
    'order.modal.totalPayableCod': 'Total (Cash on Delivery)',
    'order.button.processingPayment': 'Processing payment…',
    'order.button.payConfirm': 'Pay & Confirm Order',
    'order.button.confirmCod': 'Confirm Order (COD)',

    // Farmer Dashboard
    'dashboard.title': 'Farmer Control Panel',
    'dashboard.subtitle': 'Manage your harvest listings and track orders',
    'dashboard.createListing': 'Create New Listing',
    'dashboard.myListings': 'My Listings',
    'dashboard.demandForecast': 'AI Demand Forecast',
    'dashboard.noListings': 'No listings yet',
    'dashboard.startSelling': 'Create your first listing to start selling',
    'dashboard.crop': 'Crop Name',
    'dashboard.quantity': 'Quantity',
    'dashboard.unit': 'Unit',
    'dashboard.pricePerUnit': 'Price per Unit (₹)',
    'dashboard.location': 'Pickup Location',
    'dashboard.description': 'Description',
    'dashboard.predictedDemand': 'Predicted Demand',
    'dashboard.confidence': 'Confidence',
    'dashboard.suggestedPrice': 'Suggested Price',
    'dashboard.next7Days': 'next 7 days',

    // Orders Page
    'orders.title': 'My Orders',
    'orders.titleReceived': 'Orders Received',
    'orders.subtitle': 'Track your farm-fresh produce orders',
    'orders.subtitleReceived': 'Orders placed by buyers on your listed harvests',
    'orders.totalOrders': 'Total Orders',
    'orders.noOrders': 'No orders yet',
    'orders.noOrdersBuyer': 'Browse the marketplace to place your first order',
    'orders.noOrdersFarmer': 'When buyers order from your listings, they will appear here',
    'orders.browseMarketplace': 'Browse Marketplace',
    'orders.viewListings': 'View My Listings',
    'orders.product': 'Product',
    'orders.seller': 'Seller',
    'orders.buyer': 'Buyer',
    'orders.delivery': 'Delivery',
    'orders.routeOptimized': 'Route optimized via AI',
    'orders.aiUnavailable': 'AI service unavailable',
    'orders.sameDayDelivery': 'Same Day Delivery',
    'orders.trackOrder': 'Track Order',
    'orders.viewRoute': '& View Route',
    'orders.confirmOrder': 'Confirm Order',
    'orders.markShipped': 'Mark Shipped',
    'orders.markDelivered': 'Mark Delivered',
    'orders.cancelOrder': 'Cancel Order',
    'orders.status.pending': 'Pending',
    'orders.status.confirmed': 'Confirmed',
    'orders.status.shipped': 'Shipped',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'orders.payment.paid': 'Paid',
    'orders.payment.cod': 'Pay on delivery',

    // Order Tracking
    'tracking.title': 'Live Order & Logistics Status',
    'tracking.subtitle': 'LIVE CONSIGNMENT DISPATCH TRACKER',
    'tracking.gpsLinked': 'GPS Satellite Linked',
    'tracking.orderTracked': 'Order Tracked',
    'tracking.totalAmount': 'Total Amount',
    'tracking.payment': 'Payment',
    'tracking.aiRoute': 'AI-OPTIMIZED DELIVERY ROUTE',
    'tracking.distance': 'Distance',
    'tracking.estTime': 'Est. Time',
    'tracking.logisticsCost': 'Logistics Cost',
    'tracking.optimizedWaypoints': 'Optimized Waypoints:',
    'tracking.dispatchSchedule': 'DISPATCH ON SCHEDULE',
    'tracking.eta': 'ETA',
    'tracking.inTransit': 'Your order is in transit via optimized route.',
    'tracking.contactSupport': 'Contact Support',
    'tracking.orderConfirmed': 'Order Confirmed',
    'tracking.routeOptimized': 'Route Optimized & Dispatch Ready',
    'tracking.inTransitTitle': 'In Transit',
    'tracking.delivered': 'Delivered',
    'tracking.farmOrigin': 'Farm Origin',
    'tracking.optimizedRoute': 'Optimized Route',
    'tracking.awaitingDispatch': 'Awaiting dispatch confirmation',
    'tracking.pending': 'Pending',
    'tracking.routeInProgress': 'Route optimization in progress',
    'tracking.directRoute': 'Direct delivery route',
    'tracking.liveTransit': 'Live Transit',
    'tracking.awaitingShipment': 'Awaiting Shipment',
    'tracking.viaRoute': 'Via',
    'tracking.waypointsOptimized': 'waypoints optimized for fastest delivery',
    'tracking.multiStopActive': 'Multi-stop optimization active',
    'tracking.deliveryTo': 'Delivery to',
    'tracking.estimatedArrival': 'Estimated arrival',
    'tracking.otpVerification': 'Contactless handover with OTP verification',
    'tracking.noOrderSelected': 'No Order Selected',
    'tracking.orderNotFound': 'Order Not Found',
    'tracking.selectOrder': 'Please select an order from your orders page to view tracking details.',
    'tracking.orderNotFoundMsg': 'The order you are looking for could not be found.',
    'tracking.viewMyOrders': 'View My Orders',

    // Tracking extras
    'tracking.loading': 'Loading order details...',
    'tracking.banner.tagline': 'LIVE CONSIGNMENT DISPATCH TRACKER',
    'tracking.banner.title': 'Live Order & Logistics Status',
    'tracking.badge.gpsLinked': 'GPS Satellite Linked',
    'tracking.badge.tracked': 'Order Tracked',
    'tracking.route.heading': 'AI-OPTIMIZED DELIVERY ROUTE',
    'tracking.route.distance': 'Distance',
    'tracking.route.estTime': 'Est. Time',
    'tracking.route.minutes': ' mins',
    'tracking.route.cost': 'Logistics Cost',
    'tracking.route.waypointsLabel': 'Optimized Waypoints:',
    'tracking.dispatch.onSchedule': 'DISPATCH ON SCHEDULE',
    'tracking.dispatch.etaMins': '(ETA:',
    'tracking.dispatch.inTransitDesc': 'Your order is in transit via optimized route.',
    'tracking.badge.directExpress': 'Direct Express',
    'tracking.steps.orderConfirmed': 'Order Confirmed',
    'tracking.steps.farmOrigin': 'Farm Producer',
    'tracking.steps.dispatchReady': 'Route Optimized & Dispatch Ready',
    'tracking.steps.optimizedRoute': 'Optimized Route:',
    'tracking.steps.awaitingDispatch': 'Awaiting dispatch confirmation',
    'tracking.steps.etaCost': 'ETA:',
    'tracking.steps.optimizing': 'Route optimization in progress',
    'tracking.steps.inTransit': 'In Transit',
    'tracking.steps.viaRoute': 'Via:',
    'tracking.steps.directRoute': 'Direct delivery route',
    'tracking.steps.liveTransit': 'Live Transit',
    'tracking.steps.awaitingShipment': 'Awaiting Shipment',
    'tracking.steps.waypointsOptimized': 'waypoints optimized for fastest delivery',
    'tracking.steps.multiStopActive': 'Multi-stop optimization active',
    'tracking.steps.delivered': 'Delivered',
    'tracking.steps.deliveryTo': 'Delivery to:',
    'tracking.steps.estimatedArrival': 'Estimated arrival',
    'tracking.steps.otpVerification': 'Contactless handover with OTP verification',
    'tracking.error.noOrderId': 'No order ID provided',
    'tracking.error.notFound': 'Order not found',
    'tracking.error.loadFailed': 'Failed to load order details',
    'tracking.error.noOrderSelectedTitle': 'No Order Selected',
    'tracking.error.notFoundTitle': 'Order Not Found',
    'tracking.error.noOrderSelectedDesc': 'Please select an order from your orders page to view tracking details.',
    'tracking.error.notFoundDesc': 'The order you are looking for could not be found.',
    'tracking.button.viewMyOrders': 'View My Orders',
    'tracking.button.contactSupport': 'Contact Support',

    // Farmer / Dashboard extras
    'farmer.demand.high': 'High Mandi Demand',
    'farmer.demand.active': 'Active in Mandi',
    'farmer.demand.removed': 'Removed from Marketplace',
    'farmer.status.active': 'Active in Mandi',
    'farmer.status.removed': 'Removed',
    'farmer.alert.invalidPriceQty': 'Please enter valid price and quantity.',
    'farmer.alert.updateFailed': 'Failed to update listing:',
    'farmer.alert.removeFailed': 'Failed to remove listing:',
    'farmer.alert.cropListedSuccess': 'Crop listed successfully! It is now visible to buyers in the marketplace.',
    'farmer.alert.cropListFailed': 'Failed to list crop:',
    'farmer.stats.grossRevenue': 'Gross Mandi Revenue',
    'farmer.stats.noSales': 'No sales yet',
    'farmer.stats.bankSettlement': 'Direct to Bank Account',
    'farmer.stats.activeCrops': 'Active Listed Crops',
    'farmer.stats.listedOnMandi': 'Listed on mandi',
    'farmer.stats.listCropsPrompt': 'List crops to sell',
    'farmer.stats.readyProcurement': 'Ready for procurement',
    'farmer.stats.totalShipments': 'Total Shipments',
    'farmer.stats.allCompleted': 'All completed',
    'farmer.stats.noDeliveries': 'No deliveries yet',
    'farmer.stats.completedOrders': 'Completed orders',
    'farmer.banner.tagline': 'KISAN & FPO PRODUCER DASHBOARD',
    'farmer.banner.title': 'Farm Operations & Direct Sales Hub',
    'farmer.banner.desc': 'Manage your crop inventory, track live market demand, and view transparent UPI settlement logs.',
    'farmer.button.listNewCrop': 'List New Crop',
    'farmer.button.listFirstCrop': 'List Your First Crop',
    'farmer.button.adjust': 'Adjust',
    'farmer.button.registerCrop': 'Register Crop',
    'farmer.button.removeListing': 'Remove Listing',
    'farmer.inventory.heading': 'Active Harvest Batches',
    'farmer.inventory.registeredLots': 'Registered Lots',
    'farmer.inventory.emptyTitle': 'No crops listed yet',
    'farmer.inventory.emptyDesc': 'You haven\'t listed any crops yet. Add your own harvest to start selling directly to buyers in the marketplace.',
    'farmer.inventory.available': 'Available:',
    'farmer.inventory.mandiDemand': 'Mandi Demand:',
    'farmer.intelligence.title': 'Mandi Demand Intelligence',
    'farmer.intelligence.noDataTitle': 'No order data yet',
    'farmer.intelligence.noDataDesc': 'Mandi demand intelligence and payout charts will appear once buyers start placing orders on your listings.',
    'farmer.intelligence.orderSummary': 'ORDER SUMMARY',
    'farmer.intelligence.recentOrderValues': 'Recent Order Values',
    'farmer.intelligence.completedCount': 'completed',
    'farmer.intelligence.inProgressCount': 'in progress',
    'farmer.modal.addCropTitle': 'List New Harvest Lot',
    'farmer.modal.addCropDesc': 'Register your freshly harvested crops to the direct mandi market.',
    'farmer.modal.cropName': 'Crop / Product Name',
    'farmer.modal.cropNamePlaceholder': 'e.g. Organic Bell Peppers',
    'farmer.modal.fetchFarmFromMap': 'Fetch farm address from map',
    'farmer.modal.mapPrompt': 'Click on the map to pin your farm location',
    'farmer.modal.mapPinned': 'Farm pinned at',
    'farmer.alert.needFarmPin': 'Please pin your farm location on the map so the pickup origin is exact.',
    'farmer.modal.stockQuantity': 'Stock Quantity (kg)',
    'farmer.modal.stockPlaceholder': 'e.g. 500',
    'farmer.modal.pricePerKg': 'Price (₹ per kg)',
    'farmer.modal.pricePlaceholder': 'e.g. 45',
    'farmer.modal.qualityGrade': 'Quality Grade',
    'farmer.modal.adjustTitle': 'Adjust Listing',
    'farmer.modal.adjustDesc': 'Update price and stock for',
    'farmer.modal.pricePerUnit': 'Price (₹ per',
    'farmer.modal.stockUnit': 'Stock (',
    'farmer.grade.gradeAPlus': 'Grade A+ (Certified Organic)',
    'farmer.grade.gradeA': 'Grade A (Prime Mandi Lot)',
    'farmer.grade.gradeBPlus': 'Grade B+ (Standard Lot)',
    'farmer.confirm.removeListing': 'Remove',
    'farmer.confirm.removeListingFull': 'Remove "{name}" from your active listings? It will no longer be visible to buyers.',
    'farmer.stats.sale': 'sale',
    'farmer.stats.sales': 'sales',
    'farmer.stats.batch': 'Batch',
    'farmer.stats.batches': 'Batches',
    'farmer.stats.delivery': 'Delivery',
    'farmer.stats.deliveries': 'Deliveries',
    'farmer.summary.youHave': 'You have',
    'farmer.summary.total': 'total',
    'farmer.summary.with': ', with',
    'farmer.summary.delivered': 'delivered',
    'farmer.summary.and': 'and',
    'farmer.summary.earned': 'earned.',
    'farmer.summary.allPendingOrTransit': ' — all pending or in transit.',
    'common.order': 'order',
    'common.orders': 'orders',

    // Orders extras
    'orders.alert.statusUpdated': 'Order',
    'orders.alert.statusUpdateFailed': 'Failed to',
    'orders.auth.loginPrompt': 'Please login to view your orders',
    'orders.heading.buyerTitle': 'My Orders',
    'orders.heading.farmerTitle': 'Orders Received',
    'orders.heading.buyerDesc': 'Track your farm-fresh produce orders',
    'orders.heading.farmerDesc': 'Orders placed by buyers on your listed harvests',
    'orders.stats.totalOrders': 'Total Orders',
    'orders.empty.title': 'No orders yet',
    'orders.empty.buyerDesc': 'Browse the marketplace to place your first order',
    'orders.empty.farmerDesc': 'When buyers order from your listings, they will appear here',
    'orders.button.browseMarketplace': 'Browse Marketplace',
    'orders.button.viewMyListings': 'View My Listings',
    'orders.card.orderNumber': 'Order #',
    'orders.card.product': 'Product',
    'orders.card.sellerLabel': 'Seller',
    'orders.card.buyerLabel': 'Buyer',
    'orders.card.deliveryTo': 'Delivery To',
    'orders.card.addressNotProvided': 'Address not provided',
    'orders.card.aiRouteOptimized': 'Route optimized via AI',
    'orders.card.aiRoutePending': 'AI route assigned on confirm',
    'orders.dispatch.onTheMove': 'Dispatch on the move',
    'orders.dispatch.onItsWay': 'Your order is on its way to',
    'orders.dispatch.aiRoute': 'AI Optimized Route',
    'orders.dispatch.stops': ' stops',
    'orders.dispatch.markedAs': 'marked as',
    'orders.dispatch.statusCancelled': 'cancelled',
    'orders.auth.login': 'Login',

    // Timeline
    'timeline.orderPlaced': 'Order Placed',
    'timeline.confirmed': 'Confirmed',
    'timeline.shipped': 'Shipped',
    'timeline.delivered': 'Delivered',
    'timeline.now': 'Now',
    'timeline.currentStep': 'Current step',
    'timeline.done': 'Done',
    'timeline.waiting': 'Waiting',

    // Footer
    'footer.tagline': 'AgriConnect — Smart India Hackathon 2026',
    'footer.directTrade': 'Direct Trade Protocol Active',
    'footer.zeroMiddlemen': 'Zero Middlemen • 100% Fair Value',
  },
  hi: {
    // Navbar
    'nav.marketplace': 'मंडी बाजार',
    'nav.dashboard': 'किसान स्टूडियो',
    'nav.orders': 'ऑर्डर',
    'nav.tracking': 'डिस्पैच ट्रैक',
    'nav.login': 'लॉगिन / रजिस्टर',
    'nav.logout': 'लॉगआउट',
    'nav.tagline': 'सीधे किसान से उपभोक्ता नेटवर्क',
    'nav.role.farmer': '🌾 किसान / FPO',
    'nav.role.buyer': '🛒 खरीदार',

    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.viewAll': 'सभी देखें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.save': 'सहेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.submit': 'जमा करें',
    'common.close': 'बंद करें',
    'common.emailAddress': 'ईमेल पता',
    'common.password': 'पासवर्ड',
    'common.login': 'लॉगिन',
    'common.price': 'मूल्य',
    'common.pending': 'लंबित',
    'common.totalAmount': 'कुल राशि',
    'common.payment': 'भुगतान',
    'common.saving': 'सहेजा जा रहा है…',
    'common.saveChanges': 'परिवर्तन सहेजें',
    'common.continue': 'जारी रखें →',
    'common.confirmOrder': 'ऑर्डर की पुष्टि करें',
    'common.minutes': ' मिनट',

    // Login Page
    'login.title': 'एग्रीकनेक्ट में आपका स्वागत है',
    'login.subtitle': 'सीधे खेत से उपभोक्ता व्यापार नेटवर्क',
    'login.selectRole': 'अपनी भूमिका चुनें',
    'login.farmer': 'किसान / FPO',
    'login.farmerDesc': 'अपनी फसल सूचीबद्ध करें और खरीदारों से जुड़ें',
    'login.buyer': 'खरीदार (उपभोक्ता/थोक)',
    'login.buyerDesc': 'सीधे खेतों से ताजा उपज खरीदें',
    'login.email': 'ईमेल पता',
    'login.password': 'पासवर्ड',
    'login.name': 'पूरा नाम',
    'login.phone': 'फोन नंबर',
    'login.location': 'स्थान',
    'login.signIn': 'साइन इन करें',
    'login.signUp': 'खाता बनाएं',
    'login.switchToSignUp': 'नए उपयोगकर्ता? खाता बनाएं',
    'login.switchToSignIn': 'पहले से खाता है? साइन इन करें',

    // Login extras
    'login.badge.tagline': 'किसान से सीधा मंडी और ग्राहक',
    'login.hero.title': 'एग्रीकनेक्ट में आपका स्वागत है',
    'login.hero.description': 'कृषि उत्पादकों को उचित MSP रिटर्न और खरीदारों को प्रामाणिक खेत-ताजा आपूर्ति सुनिश्चित करने वाला सीधा व्यापार नेटवर्क।',
    'login.roleSelector.title': 'खाता प्रकार चुनें',
    'login.role.farmerTitle': 'किसान / FPO उत्पादक',
    'login.role.farmerDesc': 'फसलें सूचीबद्ध करें, मंडी मूल्य रुझान देखें और सीधे भुगतान प्राप्त करें।',
    'login.role.buyerTitle': 'खरीदार / खुदरा / थोक',
    'login.role.buyerDesc': 'लाइव कोल्ड-चेन ट्रैकिंग के साथ खेत-ताजा उपज ऑर्डर करें।',
    'login.trust.verifiedKisan': 'सत्यापित किसान आधार और FPO पंजीकरण',
    'login.trust.zeroBrokerage': 'शून्य ब्रोकरेज और सीधा बैंक UPI निपटान',
    'login.tabs.login': 'लॉगिन',
    'login.tabs.register': 'रजिस्टर',
    'login.heading.signIn': 'ईमेल से साइन इन करें',
    'login.heading.registerRoleFarmer': 'किसान / FPO के रूप में रजिस्टर करें',
    'login.heading.registerRoleBuyer': 'खरीदार के रूप में रजिस्टर करें',
    'login.subheading.signIn': 'साइन इन करने के लिए अपना ईमेल और पासवर्ड दर्ज करें।',
    'login.subheading.register': 'शुरू करने के लिए अपना मूल संपर्क और स्थान विवरण दर्ज करें।',
    'login.placeholder.email': 'जैसे farmer@example.com',
    'login.button.signingIn': 'साइन इन हो रहा है...',
    'login.button.signIn': 'साइन इन करें',
    'login.label.fullName': 'पूरा नाम / अधिकृत नाम',
    'login.placeholder.nameFarmer': 'जैसे रमेश कुमार पटेल',
    'login.placeholder.nameBuyer': 'जैसे सुनील शर्मा',
    'login.placeholder.passwordMin': 'न्यूनतम 6 अक्षर',
    'login.label.mobileNumber': 'मोबाइल नंबर',
    'login.placeholder.mobileNumber': '10-अंकीय संख्या',
    'login.label.location': 'जिला और राज्य',
    'login.placeholder.location': 'जैसे लुधियाना, पंजाब',
    'login.label.fpoName': 'FPO / सहकारी समूह का नाम (वैकल्पिक)',
    'login.placeholder.fpoName': 'जैसे मालवा किसान विकास सहकारी',
    'login.label.buyerCategory': 'खरीदार श्रेणी',
    'login.buyerType.consumer': 'व्यक्तिगत परिवार / उपभोक्ता',
    'login.buyerType.restaurant': 'रेस्टोरेंट / वाणिज्यिक रसोई',
    'login.buyerType.trader': 'थोक मंडी व्यापारी (B2B)',
    'login.buyerType.supermarket': 'खुदरा सुपरमार्केट श्रृंखला',
    'login.button.completeRegistration': 'पंजीकरण पूर्ण करें और प्रवेश करें',
    'login.footer.terms': 'साइन इन करके, आप SIH 26033 के अंतर्गत निष्पक्ष मंडी व्यापार शर्तों और सीधे निपटान नियमों से सहमत होते हैं।',
    'login.alert.enterCredentials': 'कृपया ईमेल और पासवर्ड दोनों दर्ज करें।',
    'login.alert.authFailed': 'प्रमाणीकरण विफल। कृपया अपनी साख की जांच करें।',

    // Marketplace
    'marketplace.title': 'सीधे खेत उपज बाजार',
    'marketplace.subtitle': 'खेतों से ताजा • शून्य बिचौलिए • उचित मूल्य',
    'marketplace.searchPlaceholder': 'फसल, किसान, स्थान खोजें...',
    'marketplace.noProducts': 'कोई उत्पाद नहीं मिला',
    'marketplace.browseMessage': 'जल्द ही वापस जांचें या अपने फ़िल्टर समायोजित करें',
    'marketplace.perKg': '/किलो',
    'marketplace.available': 'उपलब्ध',
    'marketplace.orderNow': 'अभी ऑर्डर करें',
    'marketplace.quantityPlaceholder': 'मात्रा (किलो)',
    'marketplace.placeOrder': 'ऑर्डर करें',
    'marketplace.totalPrice': 'कुल मूल्य',
    'marketplace.paymentMethod': 'भुगतान विधि',
    'marketplace.upi': 'UPI / कार्ड',
    'marketplace.cod': 'डिलीवरी पर नकद',

    // Marketplace extras
    'marketplace.error.addressRequired': 'कृपया डिलीवरी पता दर्ज करें।',
    'marketplace.badge.directFarm': 'सीधा फार्म',
    'marketplace.badge.organicCertified': 'ऑर्गेनिक प्रमाणित',
    'marketplace.product.stock': 'स्टॉक:',
    'marketplace.product.producer': 'उत्पादक:',
    'marketplace.product.mandiHub': 'मंडी हब 04',
    'marketplace.product.directFarmPrice': 'सीधी फार्म कीमत',
    'marketplace.product.available': 'उपलब्ध',
    'marketplace.button.buyDirect': 'सीधे खरीदें',
    'marketplace.button.sellingOnly': 'केवल बिक्री',
    'marketplace.tooltip.sellerOnly': 'विक्रेता खाते फसलें सूचीबद्ध करते हैं — ऑर्डर करने के लिए अलग खरीदार खाता उपयोग करें।',
    'marketplace.tooltip.loginRequired': 'ऑर्डर करने के लिए खरीदार के रूप में लॉगिन करें।',
    'marketplace.alert.loginRequired': 'ऑर्डर करने के लिए कृपया पहले लॉगिन करें',
    'marketplace.alert.orderSuccess': 'ऑर्डर सफलतापूर्वक दिया गया! भुगतान:',
    'marketplace.alert.orderFailed': 'ऑर्डर देने में विफल:',
    'marketplace.banner.subtag': 'सीधा फार्म मंडी बाजार • 0% बिचौलिया कमीशन',
    'marketplace.banner.title': 'खेत-ताजा मंडी फसलें',
    'marketplace.banner.desc': 'सत्यापित FPO और स्थानीय कृषि सहकारी समितियों से सीधे प्रामाणिक लॉट ब्राउज़ करें।',
    'marketplace.banner.verifiedFPOs': 'सत्यापित FPO',
    'marketplace.banner.activeFPOs': '12 सक्रिय',
    'marketplace.banner.transitEta': 'पारगमन अनुमान',
    'marketplace.banner.sameDay': 'उसी दिन',
    'marketplace.search.placeholder': 'फसल, किसान या जिला खोजें...',
    'marketplace.empty.title': 'आपकी खोज मानदंड से कोई फसल मेल नहीं खाती।',
    'marketplace.empty.clearFilters': 'फ़िल्टर साफ़ करें',
    'marketplace.button.myOrders': 'मेरे ऑर्डर',
    'category.all': 'सभी',
    'category.vegetables': 'सब्ज़ियाँ',
    'category.grains': 'अनाज',
    'category.fruits': 'फल',
    'category.dryFruits': 'सूखे मेवे',
    'category.dryfruits': 'सूखे मेवे',
    'category.other': 'अन्य',

    // Payment methods
    'payment.upi.label': 'UPI',
    'payment.upi.sub': 'GPay / PhonePe / Paytm',
    'payment.card.label': 'कार्ड',
    'payment.card.sub': 'क्रेडिट / डेबिट',
    'payment.netbanking.label': 'नेट बैंकिंग',
    'payment.netbanking.sub': 'सभी प्रमुख बैंक',
    'payment.wallet.label': 'वॉलेट',
    'payment.wallet.sub': 'Paytm / Amazon Pay',
    'payment.cod.sub': 'दरवाजे पर भुगतान करें',
    'payment.methodLabel': 'भुगतान विधि',

    // Order modal (marketplace)
    'order.modal.title': 'ऑर्डर करें',
    'order.modal.quantityIn': 'मात्रा (में',
    'order.modal.deliveryAddress': 'डिलीवरी पता',
    'order.modal.addressPlaceholder': 'मकान नंबर, गली, शहर, राज्य',
    'order.modal.saveAddressDefault': 'इसे अपना डिफ़ॉल्ट डिलीवरी पता के रूप में सहेजें',
    'order.modal.totalPayableOnline': 'कुल देय',
    'order.modal.totalPayableCod': 'कुल (डिलीवरी पर नकद)',
    'order.button.processingPayment': 'भुगतान संसाधित हो रहा है…',
    'order.button.payConfirm': 'भुगतान करें और ऑर्डर की पुष्टि करें',
    'order.button.confirmCod': 'ऑर्डर की पुष्टि करें (COD)',

    // Farmer Dashboard
    'dashboard.title': 'किसान नियंत्रण पैनल',
    'dashboard.subtitle': 'अपनी फसल सूची प्रबंधित करें और ऑर्डर ट्रैक करें',
    'dashboard.createListing': 'नई सूची बनाएं',
    'dashboard.myListings': 'मेरी सूचियां',
    'dashboard.demandForecast': 'AI मांग पूर्वानुमान',
    'dashboard.noListings': 'अभी तक कोई सूची नहीं',
    'dashboard.startSelling': 'बिक्री शुरू करने के लिए अपनी पहली सूची बनाएं',
    'dashboard.crop': 'फसल का नाम',
    'dashboard.quantity': 'मात्रा',
    'dashboard.unit': 'इकाई',
    'dashboard.pricePerUnit': 'प्रति इकाई मूल्य (₹)',
    'dashboard.location': 'पिकअप स्थान',
    'dashboard.description': 'विवरण',
    'dashboard.predictedDemand': 'अनुमानित मांग',
    'dashboard.confidence': 'विश्वास',
    'dashboard.suggestedPrice': 'सुझाया गया मूल्य',
    'dashboard.next7Days': 'अगले 7 दिन',

    // Orders Page
    'orders.title': 'मेरे ऑर्डर',
    'orders.titleReceived': 'प्राप्त ऑर्डर',
    'orders.subtitle': 'अपने खेत-ताजा उपज ऑर्डर ट्रैक करें',
    'orders.subtitleReceived': 'आपकी सूचीबद्ध फसलों पर खरीदारों द्वारा दिए गए ऑर्डर',
    'orders.totalOrders': 'कुल ऑर्डर',
    'orders.noOrders': 'अभी तक कोई ऑर्डर नहीं',
    'orders.noOrdersBuyer': 'अपना पहला ऑर्डर देने के लिए बाजार ब्राउज़ करें',
    'orders.noOrdersFarmer': 'जब खरीदार आपकी सूचियों से ऑर्डर करेंगे, तो वे यहां दिखाई देंगे',
    'orders.browseMarketplace': 'बाजार ब्राउज़ करें',
    'orders.viewListings': 'मेरी सूचियां देखें',
    'orders.product': 'उत्पाद',
    'orders.seller': 'विक्रेता',
    'orders.buyer': 'खरीदार',
    'orders.delivery': 'डिलीवरी',
    'orders.routeOptimized': 'AI द्वारा अनुकूलित मार्ग',
    'orders.aiUnavailable': 'AI सेवा अनुपलब्ध',
    'orders.sameDayDelivery': 'उसी दिन डिलीवरी',
    'orders.trackOrder': 'ऑर्डर ट्रैक करें',
    'orders.viewRoute': 'और मार्ग देखें',
    'orders.confirmOrder': 'ऑर्डर की पुष्टि करें',
    'orders.markShipped': 'शिप किया गया चिह्नित करें',
    'orders.markDelivered': 'डिलीवर किया गया चिह्नित करें',
    'orders.cancelOrder': 'ऑर्डर रद्द करें',
    'orders.status.pending': 'लंबित',
    'orders.status.confirmed': 'पुष्टि',
    'orders.status.shipped': 'भेजा गया',
    'orders.status.delivered': 'डिलीवर किया गया',
    'orders.status.cancelled': 'रद्द किया गया',
    'orders.payment.paid': 'भुगतान किया गया',
    'orders.payment.cod': 'डिलीवरी पर भुगतान',

    // Order Tracking
    'tracking.title': 'लाइव ऑर्डर और लॉजिस्टिक्स स्थिति',
    'tracking.subtitle': 'लाइव खेप प्रेषण ट्रैकर',
    'tracking.gpsLinked': 'GPS सैटेलाइट लिंक',
    'tracking.orderTracked': 'ऑर्डर ट्रैक किया गया',
    'tracking.totalAmount': 'कुल राशि',
    'tracking.payment': 'भुगतान',
    'tracking.aiRoute': 'AI-अनुकूलित डिलीवरी मार्ग',
    'tracking.distance': 'दूरी',
    'tracking.estTime': 'अनुमानित समय',
    'tracking.logisticsCost': 'लॉजिस्टिक्स लागत',
    'tracking.optimizedWaypoints': 'अनुकूलित वेपॉइंट:',
    'tracking.dispatchSchedule': 'समय पर प्रेषण',
    'tracking.eta': 'पहुंचने का समय',
    'tracking.inTransit': 'आपका ऑर्डर अनुकूलित मार्ग के माध्यम से पारगमन में है।',
    'tracking.contactSupport': 'सहायता से संपर्क करें',
    'tracking.orderConfirmed': 'ऑर्डर की पुष्टि',
    'tracking.routeOptimized': 'मार्ग अनुकूलित और प्रेषण तैयार',
    'tracking.inTransitTitle': 'पारगमन में',
    'tracking.delivered': 'डिलीवर किया गया',
    'tracking.farmOrigin': 'खेत मूल',
    'tracking.optimizedRoute': 'अनुकूलित मार्ग',
    'tracking.awaitingDispatch': 'प्रेषण पुष्टि की प्रतीक्षा में',
    'tracking.pending': 'लंबित',
    'tracking.routeInProgress': 'मार्ग अनुकूलन प्रगति में',
    'tracking.directRoute': 'सीधा डिलीवरी मार्ग',
    'tracking.liveTransit': 'लाइव पारगमन',
    'tracking.awaitingShipment': 'शिपमेंट की प्रतीक्षा में',
    'tracking.viaRoute': 'के माध्यम से',
    'tracking.waypointsOptimized': 'सबसे तेज डिलीवरी के लिए अनुकूलित वेपॉइंट',
    'tracking.multiStopActive': 'मल्टी-स्टॉप अनुकूलन सक्रिय',
    'tracking.deliveryTo': 'डिलीवरी',
    'tracking.estimatedArrival': 'अनुमानित आगमन',
    'tracking.otpVerification': 'OTP सत्यापन के साथ संपर्करहित हस्तांतरण',
    'tracking.noOrderSelected': 'कोई ऑर्डर चयनित नहीं',
    'tracking.orderNotFound': 'ऑर्डर नहीं मिला',
    'tracking.selectOrder': 'ट्रैकिंग विवरण देखने के लिए कृपया अपने ऑर्डर पृष्ठ से एक ऑर्डर चुनें।',
    'tracking.orderNotFoundMsg': 'आप जो ऑर्डर खोज रहे हैं वह नहीं मिला।',
    'tracking.viewMyOrders': 'मेरे ऑर्डर देखें',

    // Tracking extras
    'tracking.loading': 'ऑर्डर विवरण लोड हो रहा है...',
    'tracking.banner.tagline': 'लाइव खेप प्रेषण ट्रैकर',
    'tracking.banner.title': 'लाइव ऑर्डर और लॉजिस्टिक्स स्थिति',
    'tracking.badge.gpsLinked': 'GPS सैटेलाइट लिंक्ड',
    'tracking.badge.tracked': 'ऑर्डर ट्रैक किया गया',
    'tracking.route.heading': 'AI-अनुकूलित डिलीवरी मार्ग',
    'tracking.route.distance': 'दूरी',
    'tracking.route.estTime': 'अनुमानित समय',
    'tracking.route.minutes': ' मिनट',
    'tracking.route.cost': 'लॉजिस्टिक्स लागत',
    'tracking.route.waypointsLabel': 'अनुकूलित वेपॉइंट:',
    'tracking.dispatch.onSchedule': 'समय पर प्रेषण',
    'tracking.dispatch.etaMins': '(पहुंचने का समय:',
    'tracking.dispatch.inTransitDesc': 'आपका ऑर्डर अनुकूलित मार्ग के माध्यम से पारगमन में है।',
    'tracking.badge.directExpress': 'डायरेक्ट एक्सप्रेस',
    'tracking.steps.orderConfirmed': 'ऑर्डर की पुष्टि',
    'tracking.steps.farmOrigin': 'फार्म उत्पादक',
    'tracking.steps.dispatchReady': 'मार्ग अनुकूलित और प्रेषण तैयार',
    'tracking.steps.optimizedRoute': 'अनुकूलित मार्ग:',
    'tracking.steps.awaitingDispatch': 'प्रेषण पुष्टि की प्रतीक्षा में',
    'tracking.steps.etaCost': 'पहुंचने का समय:',
    'tracking.steps.optimizing': 'मार्ग अनुकूलन प्रगति में',
    'tracking.steps.inTransit': 'पारगमन में',
    'tracking.steps.viaRoute': 'के माध्यम से:',
    'tracking.steps.directRoute': 'सीधा डिलीवरी मार्ग',
    'tracking.steps.liveTransit': 'लाइव पारगमन',
    'tracking.steps.awaitingShipment': 'शिपमेंट की प्रतीक्षा में',
    'tracking.steps.waypointsOptimized': 'सबसे तेज डिलीवरी के लिए अनुकूलित वेपॉइंट',
    'tracking.steps.multiStopActive': 'मल्टी-स्टॉप अनुकूलन सक्रिय',
    'tracking.steps.delivered': 'डिलीवर किया गया',
    'tracking.steps.deliveryTo': 'डिलीवरी:',
    'tracking.steps.estimatedArrival': 'अनुमानित आगमन',
    'tracking.steps.otpVerification': 'OTP सत्यापन के साथ संपर्करहित हस्तांतरण',
    'tracking.error.noOrderId': 'कोई ऑर्डर ID प्रदान नहीं किया गया',
    'tracking.error.notFound': 'ऑर्डर नहीं मिला',
    'tracking.error.loadFailed': 'ऑर्डर विवरण लोड करने में विफल',
    'tracking.error.noOrderSelectedTitle': 'कोई ऑर्डर चयनित नहीं',
    'tracking.error.notFoundTitle': 'ऑर्डर नहीं मिला',
    'tracking.error.noOrderSelectedDesc': 'ट्रैकिंग विवरण देखने के लिए कृपया अपने ऑर्डर पृष्ठ से एक ऑर्डर चुनें।',
    'tracking.error.notFoundDesc': 'आप जो ऑर्डर खोज रहे हैं वह नहीं मिला।',
    'tracking.button.viewMyOrders': 'मेरे ऑर्डर देखें',
    'tracking.button.contactSupport': 'सहायता से संपर्क करें',

    // Farmer / Dashboard extras
    'farmer.demand.high': 'उच्च मंडी मांग',
    'farmer.demand.active': 'मंडी में सक्रिय',
    'farmer.demand.removed': 'मार्केटप्लेस से हटाया गया',
    'farmer.status.active': 'मंडी में सक्रिय',
    'farmer.status.removed': 'हटाया गया',
    'farmer.alert.invalidPriceQty': 'कृपया मान्य मूल्य और मात्रा दर्ज करें।',
    'farmer.alert.updateFailed': 'सूची अपडेट करने में विफल:',
    'farmer.alert.removeFailed': 'सूची हटाने में विफल:',
    'farmer.alert.cropListedSuccess': 'फसल सफलतापूर्वक सूचीबद्ध! यह अब बाजार में खरीदारों को दिखाई देगी।',
    'farmer.alert.cropListFailed': 'फसल सूचीबद्ध करने में विफल:',
    'farmer.stats.grossRevenue': 'कुल मंडी राजस्व',
    'farmer.stats.noSales': 'अभी कोई बिक्री नहीं',
    'farmer.stats.bankSettlement': 'सीधे बैंक खाते में',
    'farmer.stats.activeCrops': 'सक्रिय सूचीबद्ध फसलें',
    'farmer.stats.listedOnMandi': 'मंडी पर सूचीबद्ध',
    'farmer.stats.listCropsPrompt': 'बेचने के लिए फसलें सूचीबद्ध करें',
    'farmer.stats.readyProcurement': 'खरीद के लिए तैयार',
    'farmer.stats.totalShipments': 'कुल शिपमेंट',
    'farmer.stats.allCompleted': 'सभी पूर्ण',
    'farmer.stats.noDeliveries': 'अभी कोई डिलीवरी नहीं',
    'farmer.stats.completedOrders': 'पूर्ण ऑर्डर',
    'farmer.banner.tagline': 'किसान और FPO उत्पादक डैशबोर्ड',
    'farmer.banner.title': 'फार्म संचालन और सीधी बिक्री केंद्र',
    'farmer.banner.desc': 'अपनी फसल सूची प्रबंधित करें, लाइव बाजार मांग ट्रैक करें, और पारदर्शी UPI निपटान लॉग देखें।',
    'farmer.button.listNewCrop': 'नई फसल सूचीबद्ध करें',
    'farmer.button.listFirstCrop': 'अपनी पहली फसल सूचीबद्ध करें',
    'farmer.button.adjust': 'समायोजित करें',
    'farmer.button.registerCrop': 'फसल पंजीकृत करें',
    'farmer.button.removeListing': 'सूची हटाएं',
    'farmer.inventory.heading': 'सक्रिय फसल बैच',
    'farmer.inventory.registeredLots': 'पंजीकृत लॉट',
    'farmer.inventory.emptyTitle': 'अभी कोई फसल सूचीबद्ध नहीं',
    'farmer.inventory.emptyDesc': 'आपने अभी कोई फसल सूचीबद्ध नहीं की है। बाजार में खरीदारों को सीधे बेचना शुरू करने के लिए अपनी फसल जोड़ें।',
    'farmer.inventory.available': 'उपलब्ध:',
    'farmer.inventory.mandiDemand': 'मंडी मांग:',
    'farmer.intelligence.title': 'मंडी मांग बुद्धिमत्ता',
    'farmer.intelligence.noDataTitle': 'अभी तक कोई ऑर्डर डेटा नहीं',
    'farmer.intelligence.noDataDesc': 'जब खरीदार आपकी सूचियों पर ऑर्डर देना शुरू करेंगे तो मंडी मांग बुद्धिमत्ता और भुगतान चार्ट दिखाई देंगे।',
    'farmer.intelligence.orderSummary': 'ऑर्डर सारांश',
    'farmer.intelligence.recentOrderValues': 'हाल के ऑर्डर मूल्य',
    'farmer.intelligence.completedCount': 'पूर्ण',
    'farmer.intelligence.inProgressCount': 'प्रगति में',
    'farmer.modal.addCropTitle': 'नई फसल बैच सूचीबद्ध करें',
    'farmer.modal.addCropDesc': 'अपनी ताज़ी कटी फसलों को सीधे मंडी बाजार में पंजीकृत करें।',
    'farmer.modal.cropName': 'फसल / उत्पाद का नाम',
    'farmer.modal.cropNamePlaceholder': 'जैसे ऑर्गेनिक बेल पेपर',
    'farmer.modal.fetchFarmFromMap': 'खेत का पता मानचित्र से चुनें',
    'farmer.modal.mapPrompt': 'अपने खेत का स्थान मानचित्र पर चुनें',
    'farmer.modal.mapPinned': 'खेत चिह्नित',
    'farmer.alert.needFarmPin': 'कृपया मानचित्र पर अपने खेत का स्थान चुनें ताकि पिकअप स्थान सटीक हो।',
    'farmer.modal.stockQuantity': 'स्टॉक मात्रा (किलो)',
    'farmer.modal.stockPlaceholder': 'जैसे 500',
    'farmer.modal.pricePerKg': 'मूल्य (₹ प्रति किलो)',
    'farmer.modal.pricePlaceholder': 'जैसे 45',
    'farmer.modal.qualityGrade': 'गुणवत्ता ग्रेड',
    'farmer.modal.adjustTitle': 'सूची समायोजित करें',
    'farmer.modal.adjustDesc': 'इसके लिए मूल्य और स्टॉक अपडेट करें',
    'farmer.modal.pricePerUnit': 'मूल्य (₹ प्रति',
    'farmer.modal.stockUnit': 'स्टॉक (',
    'farmer.grade.gradeAPlus': 'ग्रेड A+ (प्रमाणित ऑर्गेनिक)',
    'farmer.grade.gradeA': 'ग्रेड A (प्राइम मंडी लॉट)',
    'farmer.grade.gradeBPlus': 'ग्रेड B+ (मानक लॉट)',
    'farmer.confirm.removeListing': 'हटाएं',
    'farmer.confirm.removeListingFull': 'क्या आप अपनी सक्रिय सूची में से "{name}" को हटाना चाहते हैं? यह अब खरीदारों को दिखाई नहीं देगा।',
    'farmer.stats.sale': 'बिक्री',
    'farmer.stats.sales': 'बिक्री',
    'farmer.stats.batch': 'बैच',
    'farmer.stats.batches': 'बैच',
    'farmer.stats.delivery': 'डिलीवरी',
    'farmer.stats.deliveries': 'डिलीवरियां',
    'farmer.summary.youHave': 'आपके पास',
    'farmer.summary.total': 'कुल',
    'farmer.summary.with': ', जिनमें',
    'farmer.summary.delivered': 'डिलीवरी हुई',
    'farmer.summary.and': 'और',
    'farmer.summary.earned': 'कमाए हैं।',
    'farmer.summary.allPendingOrTransit': ' — सभी लंबित या पारगमन में हैं।',
    'common.order': 'ऑर्डर',
    'common.orders': 'ऑर्डर',

    // Orders extras
    'orders.alert.statusUpdated': 'ऑर्डर',
    'orders.alert.statusUpdateFailed': 'विफल',
    'orders.auth.loginPrompt': 'अपने ऑर्डर देखने के लिए कृपया लॉगिन करें',
    'orders.heading.buyerTitle': 'मेरे ऑर्डर',
    'orders.heading.farmerTitle': 'प्राप्त ऑर्डर',
    'orders.heading.buyerDesc': 'अपने खेत-ताजा उपज ऑर्डर ट्रैक करें',
    'orders.heading.farmerDesc': 'आपकी सूचीबद्ध फसलों पर खरीदारों द्वारा दिए गए ऑर्डर',
    'orders.stats.totalOrders': 'कुल ऑर्डर',
    'orders.empty.title': 'अभी तक कोई ऑर्डर नहीं',
    'orders.empty.buyerDesc': 'अपना पहला ऑर्डर देने के लिए बाजार ब्राउज़ करें',
    'orders.empty.farmerDesc': 'जब खरीदार आपकी सूचियों से ऑर्डर करेंगे, तो वे यहां दिखाई देंगे',
    'orders.button.browseMarketplace': 'बाजार ब्राउज़ करें',
    'orders.button.viewMyListings': 'मेरी सूचियां देखें',
    'orders.card.orderNumber': 'ऑर्डर #',
    'orders.card.product': 'उत्पाद',
    'orders.card.sellerLabel': 'विक्रेता',
    'orders.card.buyerLabel': 'खरीदार',
    'orders.card.deliveryTo': 'डिलीवरी',
    'orders.card.addressNotProvided': 'पता प्रदान नहीं किया गया',
    'orders.card.aiRouteOptimized': 'AI द्वारा अनुकूलित मार्ग',
    'orders.card.aiRoutePending': 'पुष्टि पर AI मार्ग दिया गया',
    'orders.dispatch.onTheMove': 'डिस्पैच रास्ते में है',
    'orders.dispatch.onItsWay': 'आपका ऑर्डर रास्ते में है',
    'orders.dispatch.aiRoute': 'AI अनुकूलित मार्ग',
    'orders.dispatch.stops': ' स्टॉप',
    'orders.dispatch.markedAs': 'के रूप में चिह्नित',
    'orders.dispatch.statusCancelled': 'रद्द',
    'orders.auth.login': 'लॉगिन',

    // Timeline
    'timeline.orderPlaced': 'ऑर्डर दिया गया',
    'timeline.confirmed': 'पुष्टि',
    'timeline.shipped': 'भेजा गया',
    'timeline.delivered': 'डिलीवर किया गया',
    'timeline.now': 'अभी',
    'timeline.currentStep': 'वर्तमान चरण',
    'timeline.done': 'पूर्ण',
    'timeline.waiting': 'प्रतीक्षा में',

    // Footer
    'footer.tagline': 'एग्रीकनेक्ट — स्मार्ट इंडिया हैकथॉन 2026',
    'footer.directTrade': 'प्रत्यक्ष व्यापार प्रोटोकॉल सक्रिय',
    'footer.zeroMiddlemen': 'शून्य बिचौलिए • 100% उचित मूल्य',
  }
};
